name: skaffold
description: Easy and repeatable Kubernetes development
type: cli
homepage: https://github.com/GoogleContainerTools/skaffold
repository: ochairo/potions
license: Unknown
tags:
- kubernetes
binaries:
- skaffold-*
platforms:
  darwin:
    amd64:
      download_url: https://github.com/ochairo/potions/releases/download/skaffold-{version}/skaffold-{version}-darwin-x86_64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/skaffold-{version}/skaffold-{version}-darwin-x86_64.tar.gz.sha256
      requires_build: false
    arm64:
      download_url: https://github.com/ochairo/potions/releases/download/skaffold-{version}/skaffold-{version}-darwin-arm64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/skaffold-{version}/skaffold-{version}-darwin-arm64.tar.gz.sha256
      requires_build: false
  linux:
    amd64:
      download_url: https://github.com/ochairo/potions/releases/download/skaffold-{version}/skaffold-{version}-linux-amd64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/skaffold-{version}/skaffold-{version}-linux-amd64.tar.gz.sha256
      requires_build: false
    arm64:
      download_url: https://github.com/ochairo/potions/releases/download/skaffold-{version}/skaffold-{version}-linux-arm64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/skaffold-{version}/skaffold-{version}-linux-arm64.tar.gz.sha256
      requires_build: false
